name: nepanikar_data_migration
description: A simple package for managing the migation of data from the old Don't Panic app version.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  ini: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.21.7
