name: nepanikar_contacts_gen
description: Command line gen for contacts & help section for Don't Panic app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  build_verify: ^3.0.0
  freezed: ^2.1.1
  json_serializable: ^6.5.1
  lint: ^1.10.0
  test: ^1.21.7