name: nepanikar_contacts_gen
description: A simple package & command line gen for contacts & help section for Don't Panic app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  test: ^1.22.2