name: Continuous Integration / GitHub release
on:
  push:
    branches: [ main ]
  workflow_dispatch: # can be triggered manually

env:
  flutter_version: '3.0.5'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter SDK cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: ${{ runner.OS }}-flutter-${{ env.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build apk
        run: flutter build apk --release

      - name: Run prebuild script
        run: sh ./bin/ci_workflow_scripts/prebuild.sh ${{github.run_number}}

      - name: GitHub release
        uses: ncipollo/release-action@v1
        if: github.event_name != 'pull_request'
        with:
          name: Android build (dev-0.0.${{github.run_number}})
          commit: ${{ github.sha }}
          tag: dev-0.0.${{github.run_number}}
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
